# Generated by Django 4.2.1 on 2023-05-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.BigIntegerField()),
                ('street', models.CharField(max_length=50)),
                ('suburb', models.CharField(max_length=50)),
                ('postal_code', models.BigIntegerField()),
                ('city', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(max_length=20)),
                ('current_academic_level', models.BigIntegerField()),
                ('level_applying_for', models.CharField(max_length=20)),
                ('first_choice_of_sponsor', models.CharField(max_length=50)),
                ('second_choice_of_sponsor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('cellphone', models.CharField(max_length=10)),
                ('id_copy', models.CharField(max_length=13)),
                ('matric_certificate', models.CharField(max_length=10)),
                ('proof_of_income', models.CharField(max_length=10)),
            ],
        ),
    ]
