# Generated by Django 4.2.1 on 2023-06-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='physical_address',
            field=models.CharField(default=True, max_length=1000),
        ),
    ]
